Quick Fixes
kissmygritts/ndow-vendor-locations pull request #9
Opened 2021-03-29 17:56 UTC by iholl

I fixed the popup closure button, added pos_agent data to the popup and styled the vector layer by pos_agent (this might need a legend but shows which locations you can buy a license and which you can't)

2021-03-29 18:55 UTC, kissmygritts requested changes
Good work on the transparency for the close button. I comletely forgot. Great work on styling the different locations by different colors. If only we can figure out the stupid icon issue!

@iholl, check the code for some comments for fixes before accepting the pull request. Let me know if you have questions.

2021-03-29 18:55 UTC, kissmygritts commented on src/js/vendors-layer.js
> +// })
@iholl delete these lines if they aren't being used.

2021-03-29 18:55 UTC, kissmygritts commented on src/js/vendors-layer.js
> +  }
@iholl, maybe good practice to think about how you might encapsulate this into a function? Hint, the function will take `feature` as an argument.

2021-03-31 22:24 UTC, iholl commented
Resolved quick fixes, couldn't devise a function for setting the style, also removed test data from the applicaiton

2021-03-31 23:39 UTC, kissmygritts approved these changes
Thanks

2021-03-31 23:39 UTC, merged